#pragma once
#define IDI_APPICON                 101
#define IDM_OPEN                    1001
#define IDM_NEXT_IMG                1002
#define IDM_PREV_IMG                1003
#define IDM_ZOOM_IN                 1004
#define IDM_ZOOM_OUT                1005
#define IDM_FIT_TO_WINDOW           1006
#define IDM_FULLSCREEN              1007
#define IDM_DELETE_IMG              1008
#define IDM_EXIT                    1009
#define IDM_ROTATE_CW               1010
#define IDM_ROTATE_CCW              1011
#define IDM_SAVE                    1012
#define IDM_SAVE_AS                 1013
#define IDM_COPY                    1015
#define IDM_PASTE                   1016
#define IDM_OPEN_LOCATION           1017
#define IDM_ACTUAL_SIZE             1021
#define IDM_ZOOM_200                1022
#define IDM_ZOOM_300                1023
#define IDM_PROPERTIES              1027
#define IDM_SORT_BY_NAME_ASC        1028
#define IDM_SORT_BY_NAME_DESC       1029
#define IDM_SORT_BY_DATE_ASC        1030
#define IDM_SORT_BY_DATE_DESC       1031
#define IDM_SORT_BY_SIZE_ASC        1032
#define IDM_SORT_BY_SIZE_DESC       1033
#define IDM_FLIP                    1035
#define IDM_CROP                    1036
#define IDM_RESIZE                  1037

#define IDM_PREFERENCES             1039
#define IDM_KEYBINDINGS             1043

#define IDD_KEYBINDINGS_DIALOG      204
#define IDD_ZOOM_DIALOG             205
#define IDC_COMBO_ACTION            2024
#define IDC_EDIT_ZOOM               2028
#define IDC_HOTKEY_CTRL             2025
#define IDM_REFRESH                 1051 
#define IDM_UNDO                    1060
#define IDM_CENTER_IMAGE            1061
#define IDM_COMMIT_CROP             1062
#define IDM_TOGGLE_OSD              1063
#define IDM_PLAY_PAUSE              1064
#define IDM_RESUME_ANIM             1065
#define IDM_CUSTOM_ZOOM             1066
#define IDM_ANIM_NEXT_FRAME         1070
#define IDM_ANIM_PREV_FRAME         1071
#define IDM_ANIM_FIRST_FRAME        1072
#define IDM_CONTEXT_MENU            1075
#define IDM_SLIDESHOW               1076

#define IDD_RESIZE_DIALOG           201
#define IDC_EDIT_WIDTH              2001
#define IDC_EDIT_HEIGHT             2002
#define IDC_CHECK_ASPECT            2003

#define IDD_PREFERENCES_DIALOG      202
#define IDC_RADIO_BG_GREY           2004
#define IDC_RADIO_BG_BLACK          2005
#define IDC_RADIO_BG_WHITE          2006
#define IDC_RADIO_BG_TRANSPARENT    2007
#define IDC_CHECK_ALWAYS_ON_TOP     2008
#define IDC_CHECK_START_FULLSCREEN  2009
#define IDC_CHECK_SINGLE_INSTANCE   2010
#define IDC_RADIO_ZOOM_FIT          2011
#define IDC_RADIO_ZOOM_ACTUAL       2012
#define IDC_STATIC_BG_GROUP         2013
#define IDC_STATIC_APP_GROUP        2014
#define IDC_STATIC_ZOOM_GROUP       2015
#define IDC_CHECK_AUTO_REFRESH      2023  
#define IDC_CHECK_SMOOTH_SCALING    2026
#define IDC_CHECK_FADE_ANIMATION    2027
#define IDC_CHECK_SHOW_OSD          2030
#define IDC_CHECK_ASK_DELETE        2031
#define IDC_CHECK_PRESERVE_ZOOM     2032
#define IDC_RADIO_ZOOM_AUTO         2033
#define IDC_STATIC_AUTOZOOM_GROUP   2034
#define IDC_SLIDER_AUTO_MAXW        2035
#define IDC_SLIDER_AUTO_MAXH        2036
#define IDC_STATIC_AUTO_MAXW_VAL    2037
#define IDC_STATIC_AUTO_MAXH_VAL    2038
#define IDC_EDIT_AUTO_MINW          2039
#define IDC_EDIT_AUTO_MINH          2040

#define IDC_STATIC                  -1
